# Generated by Django 5.1.6 on 2025-03-16 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Param',
                'verbose_name_plural': 'Params',
            },
        ),
        migrations.CreateModel(
            name='SubParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now=True, null=True)),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.param')),
            ],
            options={
                'verbose_name': 'Sub Param',
                'verbose_name_plural': 'Sub Params',
            },
        ),
        migrations.CreateModel(
            name='ServerParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now=True, null=True)),
                ('subparam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subparam')),
            ],
            options={
                'verbose_name': 'Server Param',
                'verbose_name_plural': 'Server Params',
            },
        ),
    ]
